"""empty message

Revision ID: 15fd7a6a74bd
Revises: c269b893a528
Create Date: 2022-06-27 16:55:57.949799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15fd7a6a74bd'
down_revision = 'c269b893a528'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('royal_jelly',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.Column('royesh_giah', sa.String(length=128), nullable=False),
    sa.Column('tarigh_masraf', sa.String(length=128), nullable=False),
    sa.Column('hallal', sa.String(length=128), nullable=False),
    sa.Column('bastebandi', sa.String(length=128), nullable=False),
    sa.Column('manh_masraf', sa.String(length=128), nullable=False),
    sa.Column('khavas_darmani', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('group', sa.String(length=128), nullable=False),
    sa.Column('price', sa.String(length=128), nullable=False),
    sa.Column('image', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('royal_jelly')
    # ### end Alembic commands ###
