"""empty message

Revision ID: 21a2542afd08
Revises: 052bba9cc976
Create Date: 2022-06-12 17:00:43.636479

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '21a2542afd08'
down_revision = '052bba9cc976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mahsolat', sa.Column('price_1kg', sa.String(length=128), nullable=False))
    op.add_column('mahsolat', sa.Column('price_05kg', sa.String(length=128), nullable=False))
    op.drop_column('mahsolat', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mahsolat', sa.Column('price', mysql.VARCHAR(length=128), nullable=False))
    op.drop_column('mahsolat', 'price_05kg')
    op.drop_column('mahsolat', 'price_1kg')
    # ### end Alembic commands ###
