"""empty message

Revision ID: 714cec12b84a
Revises: ba45c1bcdc6a
Create Date: 2022-06-20 13:32:31.035649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '714cec12b84a'
down_revision = 'ba45c1bcdc6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('mahsol_title', sa.String(length=128), nullable=False),
    sa.Column('mahsol_count', sa.String(length=128), nullable=False),
    sa.Column('mahsol_card_id', sa.String(length=16), nullable=True),
    sa.Column('mahsol_description', sa.String(length=256), nullable=False),
    sa.Column('mahsol_slug', sa.String(length=128), nullable=False),
    sa.Column('mahsol_group', sa.String(length=128), nullable=False),
    sa.Column('mahsol_price', sa.String(length=128), nullable=False),
    sa.Column('mahsol_image', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card')
    # ### end Alembic commands ###
