"""empty message

Revision ID: 71ff22b72437
Revises: e59567ddfbeb
Create Date: 2022-07-01 12:36:08.674873

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '71ff22b72437'
down_revision = 'e59567ddfbeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Baremoom', 'title_2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Baremoom', sa.Column('title_2', mysql.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
