"""empty message

Revision ID: 7f49473e6cb2
Revises: fddd43cd8af4
Create Date: 2022-06-30 15:09:35.285658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f49473e6cb2'
down_revision = 'fddd43cd8af4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('mahsol_role', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'mahsol_role')
    # ### end Alembic commands ###
