"""empty message

Revision ID: 9aceebc6fb1b
Revises: 71ff22b72437
Create Date: 2022-07-02 17:26:43.811655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aceebc6fb1b'
down_revision = '71ff22b72437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gift_pack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gift_pack')
    # ### end Alembic commands ###
