"""empty message

Revision ID: 9f462a773f78
Revises: a25fbff0f613
Create Date: 2022-06-12 09:32:33.526058

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f462a773f78'
down_revision = 'a25fbff0f613'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mahsolgroups', 'image_url')
    op.drop_column('mahsolgroups', 'image_urlfor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mahsolgroups', sa.Column('image_urlfor', mysql.VARCHAR(length=512), nullable=False))
    op.add_column('mahsolgroups', sa.Column('image_url', mysql.VARCHAR(length=512), nullable=False))
    # ### end Alembic commands ###
