"""empty message

Revision ID: a25fbff0f613
Revises: 44b74a8548b5
Create Date: 2022-06-11 17:35:00.655399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a25fbff0f613'
down_revision = '44b74a8548b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'mahsolgroups', ['image'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mahsolgroups', type_='unique')
    # ### end Alembic commands ###
