"""empty message

Revision ID: a2900f194b02
Revises: 7f49473e6cb2
Create Date: 2022-06-30 17:31:59.809133

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a2900f194b02'
down_revision = '7f49473e6cb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Baremoom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.Column('tarigh_masraf', sa.String(length=128), nullable=False),
    sa.Column('hallal', sa.String(length=128), nullable=False),
    sa.Column('bastebandi', sa.String(length=128), nullable=False),
    sa.Column('manh_masraf', sa.String(length=128), nullable=False),
    sa.Column('khavas_darmani', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('group', sa.String(length=128), nullable=False),
    sa.Column('price_100g', sa.String(length=128), nullable=False),
    sa.Column('price_50g', sa.String(length=128), nullable=False),
    sa.Column('image', sa.String(length=512), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('title')
    )
    op.create_table('garde_gol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.Column('tarigh_masraf', sa.String(length=128), nullable=False),
    sa.Column('bastebandi', sa.String(length=128), nullable=False),
    sa.Column('manh_masraf', sa.String(length=128), nullable=False),
    sa.Column('khavas_darmani', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('group', sa.String(length=128), nullable=False),
    sa.Column('price_100g', sa.String(length=128), nullable=False),
    sa.Column('price_50g', sa.String(length=128), nullable=False),
    sa.Column('image', sa.String(length=512), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('title')
    )
    op.drop_column('royal_jelly', 'hallal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('royal_jelly', sa.Column('hallal', mysql.VARCHAR(length=128), nullable=False))
    op.drop_table('garde_gol')
    op.drop_table('Baremoom')
    # ### end Alembic commands ###
