"""empty message

Revision ID: a903d13359e0
Revises: eddf897cb945
Create Date: 2022-06-24 11:02:13.859567

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a903d13359e0'
down_revision = 'eddf897cb945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('image', sa.String(length=512), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('mahsol_image', sa.String(length=128), nullable=True),
    sa.Column('mahsol_link', sa.String(length=3000), nullable=True),
    sa.Column('group_mortabet', sa.String(length=128), nullable=True),
    sa.Column('content', sa.String(length=3000), nullable=False),
    sa.Column('metacontent', sa.String(length=128), nullable=False),
    sa.Column('writer', sa.String(length=128), nullable=False),
    sa.Column('date', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('title')
    )
    op.drop_index('slug', table_name='blog')
    op.drop_index('title', table_name='blog')
    op.drop_table('blog')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('image', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('slug', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('mahsol_image', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('mahsol_link', mysql.VARCHAR(length=3000), nullable=True),
    sa.Column('group_mortabet', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('content', mysql.VARCHAR(length=3000), nullable=False),
    sa.Column('metacontent', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('writer', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('date', mysql.VARCHAR(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('title', 'blog', ['title'], unique=False)
    op.create_index('slug', 'blog', ['slug'], unique=False)
    op.drop_table('blogs')
    # ### end Alembic commands ###
