"""empty message

Revision ID: af4706e3a0f7
Revises: b3e0a7692587
Create Date: 2022-06-16 13:12:16.950657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af4706e3a0f7'
down_revision = 'b3e0a7692587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mahsolat', sa.Column('royesh_giah', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mahsolat', 'royesh_giah')
    # ### end Alembic commands ###
