"""empty message

Revision ID: b3e0a7692587
Revises: bdc2cf448c2d
Create Date: 2022-06-16 13:09:32.883457

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b3e0a7692587'
down_revision = 'bdc2cf448c2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mahsolat', sa.Column('rang_asal', sa.String(length=128), nullable=False))
    op.drop_column('mahsolat', 'negahdary')
    op.drop_column('mahsolat', 'tarkibat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mahsolat', sa.Column('tarkibat', mysql.VARCHAR(length=128), nullable=False))
    op.add_column('mahsolat', sa.Column('negahdary', mysql.VARCHAR(length=128), nullable=False))
    op.drop_column('mahsolat', 'rang_asal')
    # ### end Alembic commands ###
