"""empty message

Revision ID: ba45c1bcdc6a
Revises: af4706e3a0f7
Create Date: 2022-06-19 09:39:40.556270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba45c1bcdc6a'
down_revision = 'af4706e3a0f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sliders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('image', sa.String(length=512), nullable=False),
    sa.Column('link', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sliders')
    # ### end Alembic commands ###
