"""empty message

Revision ID: bdc2cf448c2d
Revises: 21a2542afd08
Create Date: 2022-06-14 13:20:14.601990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdc2cf448c2d'
down_revision = '21a2542afd08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mahsolgroups', sa.Column('description', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mahsolgroups', 'description')
    # ### end Alembic commands ###
