"""empty message

Revision ID: c046ee2be00a
Revises: 1462532b5de9
Create Date: 2022-06-23 16:38:08.403639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c046ee2be00a'
down_revision = '1462532b5de9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monasebat', sa.Column('link', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monasebat', 'link')
    # ### end Alembic commands ###
