"""empty message

Revision ID: c269b893a528
Revises: a903d13359e0
Create Date: 2022-06-24 12:09:58.133540

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c269b893a528'
down_revision = 'a903d13359e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'mahsol_link')
    op.drop_column('blogs', 'mahsol_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('mahsol_image', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('blogs', sa.Column('mahsol_link', mysql.VARCHAR(length=3000), nullable=True))
    # ### end Alembic commands ###
