"""empty message

Revision ID: da26b43ea1c7
Revises: faaeed882c16
Create Date: 2022-06-09 22:55:05.849717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da26b43ea1c7'
down_revision = 'faaeed882c16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mahsolat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('tarkibat', sa.String(length=128), nullable=False),
    sa.Column('tarigh_masraf', sa.String(length=128), nullable=False),
    sa.Column('negahdary', sa.String(length=128), nullable=False),
    sa.Column('bastebandi', sa.String(length=128), nullable=False),
    sa.Column('manh_masraf', sa.String(length=128), nullable=False),
    sa.Column('khavas_darmani', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('group', sa.String(length=128), nullable=False),
    sa.Column('price', sa.String(length=128), nullable=False),
    sa.Column('image', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('mahsolgroups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.Column('image', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mahsolgroups')
    op.drop_table('mahsolat')
    # ### end Alembic commands ###
