"""empty message

Revision ID: e085b5ed3991
Revises: 9aceebc6fb1b
Create Date: 2022-07-03 17:29:25.996018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e085b5ed3991'
down_revision = '9aceebc6fb1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GiftpackRegister',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('title_1', sa.String(length=128), nullable=False),
    sa.Column('title_2', sa.String(length=128), nullable=False),
    sa.Column('title_3', sa.String(length=128), nullable=False),
    sa.Column('title_4', sa.String(length=128), nullable=False),
    sa.Column('title_5', sa.String(length=128), nullable=False),
    sa.Column('price_1', sa.String(length=128), nullable=False),
    sa.Column('price_2', sa.String(length=128), nullable=False),
    sa.Column('price_3', sa.String(length=128), nullable=False),
    sa.Column('price_4', sa.String(length=128), nullable=False),
    sa.Column('price_5', sa.String(length=128), nullable=False),
    sa.Column('image', sa.String(length=128), nullable=False),
    sa.Column('bastebandi_color', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('GiftpackRegister')
    # ### end Alembic commands ###
