"""empty message

Revision ID: e59567ddfbeb
Revises: a2900f194b02
Create Date: 2022-07-01 12:34:10.790732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e59567ddfbeb'
down_revision = 'a2900f194b02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Baremoom', sa.Column('title_2', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Baremoom', 'title_2')
    # ### end Alembic commands ###
