"""empty message

Revision ID: eddf897cb945
Revises: c046ee2be00a
Create Date: 2022-06-23 18:52:25.985794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eddf897cb945'
down_revision = 'c046ee2be00a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('image', sa.String(length=512), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('mahsol_image', sa.String(length=128), nullable=True),
    sa.Column('mahsol_link', sa.String(length=3000), nullable=True),
    sa.Column('group_mortabet', sa.String(length=128), nullable=True),
    sa.Column('content', sa.String(length=3000), nullable=False),
    sa.Column('metacontent', sa.String(length=128), nullable=False),
    sa.Column('writer', sa.String(length=128), nullable=False),
    sa.Column('date', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog')
    # ### end Alembic commands ###
