"""empty message

Revision ID: faaeed882c16
Revises: 971b9e17b515
Create Date: 2022-06-06 15:23:36.661810

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'faaeed882c16'
down_revision = '971b9e17b515'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('phone_number', table_name='users')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', mysql.VARCHAR(length=128), nullable=False))
    op.create_index('phone_number', 'users', ['phone_number'], unique=False)
    # ### end Alembic commands ###
