"""empty message

Revision ID: fddd43cd8af4
Revises: 18f625d3324c
Create Date: 2022-06-30 15:02:44.634850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fddd43cd8af4'
down_revision = '18f625d3324c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mahsolat', sa.Column('role', sa.Integer(), nullable=False))
    op.add_column('royal_jelly', sa.Column('role', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('royal_jelly', 'role')
    op.drop_column('mahsolat', 'role')
    # ### end Alembic commands ###
